import type { EventItem } from "@/types/database";

export const DEFAULT_LAHORE_TECH_EVENTS: EventItem[] = [
  {
    id: "lahore-ai-summit-2026",
    title: "Lahore Generative AI Summit & Hackathon",
    slug: "lahore-generative-ai-summit-hackathon",
    description: `Join over 500 AI researchers, machine learning engineers, and founders at the flagship Lahore Generative AI Summit.\n\nFeaturing keynotes on LLM architectures, fine-tuning reasoning models, multi-agent frameworks, and local AI infrastructure in Pakistan. A 24-hour hands-on hackathon will run concurrently with prizes sponsored by leading tech venture firms.\n\nKey Highlights:\n- Technical deep dives on synthetic data generation and agentic workflows\n- Hands-on workshops with industry practitioners\n- Lightning talks from Lahore's fastest-growing AI startups\n- Dedicated founder & investor networking lounge`,
    short_description: "The premier AI conference and 24-hour builder hackathon bringing together AI engineers, researchers, and founders.",
    category: "AI & Machine Learning",
    date_start: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    date_end: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    time_display: "09:30 AM - 06:00 PM PKT",
    venue_name: "Arfa Software Technology Park, Level 3 Auditorium",
    venue_address: "346-B, Main Ferozepur Road, Nishtar Town",
    city_area: "Ferozepur Road",
    map_url: "https://maps.google.com/?q=Arfa+Software+Technology+Park+Lahore",
    registration_url: "https://luma.com",
    organizer_id: "org-1",
    image_url: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80",
    status: "approved",
    rejection_reason: null,
    featured: true,
    price_type: "free",
    price_amount: 0,
    tags: ["ArtificialIntelligence", "Hackathon", "LLMs", "DevCommunity", "FreeEntry"],
    views_count: 1420,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    organizer: {
      id: "org-1",
      email: "team@pylahore.org",
      full_name: "PyLahore & AI Collective",
      avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
      role: "admin",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: "react-pakistan-lahore-2026",
    title: "React & Next.js Lahore Developers Meetup",
    slug: "react-nextjs-lahore-developers-meetup",
    description: `A focused evening for frontend engineers and full-stack TypeScript developers. We will explore Next.js Server Actions, React 19 architecture patterns, performance optimization for high-scale apps, and design systems.\n\nAgenda:\n- Keynote: Modern React Architecture & Server Components in Production\n- Lightning talks from local engineering leads\n- Open mic for side projects\n- High-tea and networking`,
    short_description: "Deep dive into React 19, Next.js App Router, Tailwind v4, and web performance with frontend architects.",
    category: "Web Development",
    date_start: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    date_end: null,
    time_display: "05:30 PM - 08:30 PM PKT",
    venue_name: "COLABS Gulberg",
    venue_address: "4th Floor, 50-N, Gurumangat Rd, Gulberg II",
    city_area: "Gulberg",
    map_url: "https://maps.google.com/?q=COLABS+Gulberg+Lahore",
    registration_url: "https://luma.com",
    organizer_id: "org-2",
    image_url: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80",
    status: "approved",
    rejection_reason: null,
    featured: true,
    price_type: "free",
    price_amount: 0,
    tags: ["React", "Nextjs", "TypeScript", "Frontend", "Networking"],
    views_count: 890,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    organizer: {
      id: "org-2",
      email: "hello@reactlahore.dev",
      full_name: "React Lahore Community",
      avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
      role: "admin",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: "lahore-founder-mixer-daftarkhwan",
    title: "Lahore Tech Founders & Angel Mixer",
    slug: "lahore-tech-founders-angel-mixer",
    description: `An invite-friendly networking event designed for early-stage tech founders, CTOs, and angel investors active in Pakistan's ecosystem.\n\nCasual fireside discussions on seed funding rounds, unit economics, building global SaaS products from Lahore, and remote engineering hiring.`,
    short_description: "Curated networking evening for startup founders, CTOs, and venture investors in Lahore.",
    category: "Startups & Venture",
    date_start: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000).toISOString(),
    date_end: null,
    time_display: "06:00 PM - 09:00 PM PKT",
    venue_name: "Daftarkhwan Downtown",
    venue_address: "Mall of Lahore, Park Lane Tower, Tufail Rd, Cantt",
    city_area: "Cantt",
    map_url: "https://maps.google.com/?q=Daftarkhwan+Downtown+Lahore",
    registration_url: "https://luma.com",
    organizer_id: "org-3",
    image_url: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80",
    status: "approved",
    rejection_reason: null,
    featured: true,
    price_type: "paid",
    price_amount: 1500,
    tags: ["Startups", "VentureCapital", "Founders", "LahoreEcosystem"],
    views_count: 1120,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    organizer: {
      id: "org-3",
      email: "events@daftarkhwan.com",
      full_name: "Daftarkhwan Community",
      avatar_url: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=200&q=80",
      role: "user",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: "cloud-native-devops-lahore",
    title: "Cloud Native & Kubernetes Meetup Lahore",
    slug: "cloud-native-kubernetes-meetup-lahore",
    description: `Hands-on technical sessions covering Kubernetes on production clusters, cost governance in AWS/GCP, automated CI/CD pipelines, and observability with OpenTelemetry.\n\nBring your laptop for the interactive debugging session led by certified Kubernetes administrators.`,
    short_description: "Master container orchestration, cloud infrastructure, and zero-downtime deployment pipelines.",
    category: "Cloud & DevOps",
    date_start: new Date(Date.now() + 11 * 24 * 60 * 60 * 1000).toISOString(),
    date_end: null,
    time_display: "03:00 PM - 06:30 PM PKT",
    venue_name: "Kickstart Gulberg 62-C2",
    venue_address: "62-C2, Gulberg III, Near Ghalib Market",
    city_area: "Gulberg",
    map_url: "https://maps.google.com/?q=Kickstart+Gulberg+Lahore",
    registration_url: "https://luma.com",
    organizer_id: "org-4",
    image_url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    status: "approved",
    rejection_reason: null,
    featured: false,
    price_type: "free",
    price_amount: 0,
    tags: ["Cloud", "Kubernetes", "DevOps", "AWS", "Docker"],
    views_count: 650,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    organizer: {
      id: "org-4",
      email: "organizers@devopslahore.com",
      full_name: "DevOps Lahore Group",
      avatar_url: null,
      role: "user",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: "product-design-critique-lahore",
    title: "Lahore Product & Design Systems Roundtable",
    slug: "lahore-product-design-systems-roundtable",
    description: `A collaborative session for UI/UX designers, design system engineers, and product managers. We will review real-world design tokens, Figma variables, accessibility audits, and design-to-code workflows in modern tech teams.`,
    short_description: "Collaborative design critique, Figma token workflows, and accessibility standards for product designers.",
    category: "Design & Product",
    date_start: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    date_end: null,
    time_display: "04:00 PM - 07:00 PM PKT",
    venue_name: "Daftarkhwan Vogue",
    venue_address: "Vogue Towers, MM Alam Road, Gulberg III",
    city_area: "MM Alam Road",
    map_url: "https://maps.google.com/?q=Vogue+Towers+Lahore",
    registration_url: "https://luma.com",
    organizer_id: "org-5",
    image_url: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=1200&q=80",
    status: "approved",
    rejection_reason: null,
    featured: false,
    price_type: "free",
    price_amount: 0,
    tags: ["Design", "UIUX", "Figma", "DesignSystems", "Product"],
    views_count: 480,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    organizer: {
      id: "org-5",
      email: "design@lahorecreatives.com",
      full_name: "UX Lahore Guild",
      avatar_url: null,
      role: "user",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: "ethical-hacking-cybersecurity-lahore",
    title: "Cybersecurity Workshop: Defensive Security & Red Teaming",
    slug: "cybersecurity-workshop-defensive-security-red-teaming",
    description: `Hands-on penetration testing and defensive security workshop covering web application security (OWASP Top 10), vulnerability hunting, API security auditing, and cloud identity threat modeling.`,
    short_description: "Hands-on penetration testing, API vulnerability assessment, and threat detection workshop.",
    category: "Cybersecurity",
    date_start: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
    date_end: null,
    time_display: "10:00 AM - 02:00 PM PKT",
    venue_name: "FAST NUCES Computer Labs",
    venue_address: "Block B, Faisal Town",
    city_area: "Faisal Town",
    map_url: "https://maps.google.com/?q=FAST+NUCES+Lahore",
    registration_url: "https://luma.com",
    organizer_id: "org-6",
    image_url: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80",
    status: "approved",
    rejection_reason: null,
    featured: false,
    price_type: "free",
    price_amount: 0,
    tags: ["Cybersecurity", "InfoSec", "EthicalHacking", "OWASP"],
    views_count: 730,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    organizer: {
      id: "org-6",
      email: "cyber@fast.nu.edu.pk",
      full_name: "FAST Computing Society",
      avatar_url: null,
      role: "user",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
];
